version: '3.4'

services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pa$$w0rd
      - POSTGRES_DB=AuctionDb
    ports:
      - 5432:5432
    restart: always 
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mongodb:
    container_name: mongodb    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Pa$$w0rd
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data